package server;


/**
* server/AppointmentTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HospitalServer.idl
* Sunday, 20 February, 2022 11:09:53 PM EST
*/

abstract public class AppointmentTypeHelper
{
  private static String  _id = "IDL:server/AppointmentType:1.0";

  public static void insert (org.omg.CORBA.Any a, server.AppointmentType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static server.AppointmentType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (server.AppointmentTypeHelper.id (), "AppointmentType", new String[] { "PHYSICIAN", "SURGEON", "DENTAL"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static server.AppointmentType read (org.omg.CORBA.portable.InputStream istream)
  {
    return server.AppointmentType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, server.AppointmentType value)
  {
    ostream.write_long (value.value ());
  }

}
