package server;

/**
* server/AppointmentTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HospitalServer.idl
* Sunday, 20 February, 2022 11:09:53 PM EST
*/

public final class AppointmentTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public server.AppointmentType value = null;

  public AppointmentTypeHolder ()
  {
  }

  public AppointmentTypeHolder (server.AppointmentType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.AppointmentTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.AppointmentTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.AppointmentTypeHelper.type ();
  }

}
