package server;


/**
* server/HospitalServerInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HospitalServer.idl
* Sunday, 20 February, 2022 11:09:53 PM EST
*/

public interface HospitalServerInterfaceOperations 
{
  String addAppointment (String appointmentID, server.AppointmentType appointmentType, int capacity);
  String removeAppointment (String appointmentID, server.AppointmentType appointmentType);
  String listAppointmentAvailability (server.AppointmentType appointmentType);
  String bookAppointment (String patientID, String appointmentID, server.AppointmentType appointmentType);
  String getAppointmentSchedule (String patientID);
  String cancelAppointment (String patientID, String appointmentID);
  String swapAppointment (String patientID, String oldAppointmentID, server.AppointmentType oldAppointmentType, String newAppointmentID, server.AppointmentType newAppointmentType);
  void shutdown ();
} // interface HospitalServerInterfaceOperations
