package server;


/**
* server/HospitalServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HospitalServer.idl
* Sunday, 20 February, 2022 11:09:53 PM EST
*/

public interface HospitalServerInterface extends HospitalServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HospitalServerInterface
