package server;

/**
* server/HospitalServerInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HospitalServer.idl
* Sunday, 20 February, 2022 11:09:53 PM EST
*/

public final class HospitalServerInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public server.HospitalServerInterface value = null;

  public HospitalServerInterfaceHolder ()
  {
  }

  public HospitalServerInterfaceHolder (server.HospitalServerInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = server.HospitalServerInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    server.HospitalServerInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return server.HospitalServerInterfaceHelper.type ();
  }

}
